import type { Metadata } from "next";
import Hydration from "@/components/Hydration";
import localFont from "next/font/local";
import Providers from "./provider";
import { Toaster } from "sonner";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LanguagesType, routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import "./globals.css";

interface Props {
  children: React.ReactNode;
  params: { locale: LanguagesType };
  modal: React.ReactNode;
}

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
  params: { locale },
}: Readonly<Props>) {
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <Toaster />
          <Hydration />
          <Providers>
            <div id="modal-root"></div>
            {children}
          </Providers>
          {modal}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
